// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: admin.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, email, is_admin, organization_id, created_at
FROM users
ORDER BY created_at DESC
`

type ListAllUsersRow struct {
	ID             uuid.UUID     `json:"id"`
	Email          string        `json:"email"`
	IsAdmin        bool          `json:"is_admin"`
	OrganizationID uuid.NullUUID `json:"organization_id"`
	CreatedAt      sql.NullTime  `json:"created_at"`
}

func (q *Queries) ListAllUsers(ctx context.Context) ([]ListAllUsersRow, error) {
	rows, err := q.query(ctx, q.listAllUsersStmt, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUsersRow
	for rows.Next() {
		var i ListAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.IsAdmin,
			&i.OrganizationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, owner_id, plan, billing_email, is_paid
FROM organizations
ORDER BY name
`

type ListOrganizationsRow struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	OwnerID      uuid.UUID      `json:"owner_id"`
	Plan         sql.NullString `json:"plan"`
	BillingEmail sql.NullString `json:"billing_email"`
	IsPaid       bool           `json:"is_paid"`
}

func (q *Queries) ListOrganizations(ctx context.Context) ([]ListOrganizationsRow, error) {
	rows, err := q.query(ctx, q.listOrganizationsStmt, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationsRow
	for rows.Next() {
		var i ListOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.Plan,
			&i.BillingEmail,
			&i.IsPaid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAdmin = `-- name: SetUserAdmin :exec
UPDATE users
SET is_admin = true
WHERE email = $1
`

func (q *Queries) SetUserAdmin(ctx context.Context, email string) error {
	_, err := q.exec(ctx, q.setUserAdminStmt, setUserAdmin, email)
	return err
}
