// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createInviteStmt, err = db.PrepareContext(ctx, createInvite); err != nil {
		return nil, fmt.Errorf("error preparing query CreateInvite: %w", err)
	}
	if q.createOrganizationStmt, err = db.PrepareContext(ctx, createOrganization); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrganization: %w", err)
	}
	if q.createPasswordResetStmt, err = db.PrepareContext(ctx, createPasswordReset); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePasswordReset: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteInviteStmt, err = db.PrepareContext(ctx, deleteInvite); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteInvite: %w", err)
	}
	if q.deletePasswordResetStmt, err = db.PrepareContext(ctx, deletePasswordReset); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePasswordReset: %w", err)
	}
	if q.getInviteByTokenStmt, err = db.PrepareContext(ctx, getInviteByToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetInviteByToken: %w", err)
	}
	if q.getOrgMembersStmt, err = db.PrepareContext(ctx, getOrgMembers); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrgMembers: %w", err)
	}
	if q.getOrganizationStmt, err = db.PrepareContext(ctx, getOrganization); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrganization: %w", err)
	}
	if q.getPasswordResetByTokenStmt, err = db.PrepareContext(ctx, getPasswordResetByToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetPasswordResetByToken: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.listAllUsersStmt, err = db.PrepareContext(ctx, listAllUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllUsers: %w", err)
	}
	if q.listInvitesForOrgStmt, err = db.PrepareContext(ctx, listInvitesForOrg); err != nil {
		return nil, fmt.Errorf("error preparing query ListInvitesForOrg: %w", err)
	}
	if q.listOrganizationsStmt, err = db.PrepareContext(ctx, listOrganizations); err != nil {
		return nil, fmt.Errorf("error preparing query ListOrganizations: %w", err)
	}
	if q.markInviteUsedStmt, err = db.PrepareContext(ctx, markInviteUsed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkInviteUsed: %w", err)
	}
	if q.setUserAdminStmt, err = db.PrepareContext(ctx, setUserAdmin); err != nil {
		return nil, fmt.Errorf("error preparing query SetUserAdmin: %w", err)
	}
	if q.updateOrganizationBillingStmt, err = db.PrepareContext(ctx, updateOrganizationBilling); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOrganizationBilling: %w", err)
	}
	if q.updateUserOrgStmt, err = db.PrepareContext(ctx, updateUserOrg); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserOrg: %w", err)
	}
	if q.updateUserPasswordStmt, err = db.PrepareContext(ctx, updateUserPassword); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPassword: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createInviteStmt != nil {
		if cerr := q.createInviteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createInviteStmt: %w", cerr)
		}
	}
	if q.createOrganizationStmt != nil {
		if cerr := q.createOrganizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrganizationStmt: %w", cerr)
		}
	}
	if q.createPasswordResetStmt != nil {
		if cerr := q.createPasswordResetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPasswordResetStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteInviteStmt != nil {
		if cerr := q.deleteInviteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteInviteStmt: %w", cerr)
		}
	}
	if q.deletePasswordResetStmt != nil {
		if cerr := q.deletePasswordResetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePasswordResetStmt: %w", cerr)
		}
	}
	if q.getInviteByTokenStmt != nil {
		if cerr := q.getInviteByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getInviteByTokenStmt: %w", cerr)
		}
	}
	if q.getOrgMembersStmt != nil {
		if cerr := q.getOrgMembersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrgMembersStmt: %w", cerr)
		}
	}
	if q.getOrganizationStmt != nil {
		if cerr := q.getOrganizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrganizationStmt: %w", cerr)
		}
	}
	if q.getPasswordResetByTokenStmt != nil {
		if cerr := q.getPasswordResetByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPasswordResetByTokenStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.listAllUsersStmt != nil {
		if cerr := q.listAllUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllUsersStmt: %w", cerr)
		}
	}
	if q.listInvitesForOrgStmt != nil {
		if cerr := q.listInvitesForOrgStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listInvitesForOrgStmt: %w", cerr)
		}
	}
	if q.listOrganizationsStmt != nil {
		if cerr := q.listOrganizationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listOrganizationsStmt: %w", cerr)
		}
	}
	if q.markInviteUsedStmt != nil {
		if cerr := q.markInviteUsedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markInviteUsedStmt: %w", cerr)
		}
	}
	if q.setUserAdminStmt != nil {
		if cerr := q.setUserAdminStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setUserAdminStmt: %w", cerr)
		}
	}
	if q.updateOrganizationBillingStmt != nil {
		if cerr := q.updateOrganizationBillingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOrganizationBillingStmt: %w", cerr)
		}
	}
	if q.updateUserOrgStmt != nil {
		if cerr := q.updateUserOrgStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserOrgStmt: %w", cerr)
		}
	}
	if q.updateUserPasswordStmt != nil {
		if cerr := q.updateUserPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserPasswordStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                            DBTX
	tx                            *sql.Tx
	createInviteStmt              *sql.Stmt
	createOrganizationStmt        *sql.Stmt
	createPasswordResetStmt       *sql.Stmt
	createUserStmt                *sql.Stmt
	deleteInviteStmt              *sql.Stmt
	deletePasswordResetStmt       *sql.Stmt
	getInviteByTokenStmt          *sql.Stmt
	getOrgMembersStmt             *sql.Stmt
	getOrganizationStmt           *sql.Stmt
	getPasswordResetByTokenStmt   *sql.Stmt
	getUserByEmailStmt            *sql.Stmt
	getUserByIDStmt               *sql.Stmt
	listAllUsersStmt              *sql.Stmt
	listInvitesForOrgStmt         *sql.Stmt
	listOrganizationsStmt         *sql.Stmt
	markInviteUsedStmt            *sql.Stmt
	setUserAdminStmt              *sql.Stmt
	updateOrganizationBillingStmt *sql.Stmt
	updateUserOrgStmt             *sql.Stmt
	updateUserPasswordStmt        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                            tx,
		tx:                            tx,
		createInviteStmt:              q.createInviteStmt,
		createOrganizationStmt:        q.createOrganizationStmt,
		createPasswordResetStmt:       q.createPasswordResetStmt,
		createUserStmt:                q.createUserStmt,
		deleteInviteStmt:              q.deleteInviteStmt,
		deletePasswordResetStmt:       q.deletePasswordResetStmt,
		getInviteByTokenStmt:          q.getInviteByTokenStmt,
		getOrgMembersStmt:             q.getOrgMembersStmt,
		getOrganizationStmt:           q.getOrganizationStmt,
		getPasswordResetByTokenStmt:   q.getPasswordResetByTokenStmt,
		getUserByEmailStmt:            q.getUserByEmailStmt,
		getUserByIDStmt:               q.getUserByIDStmt,
		listAllUsersStmt:              q.listAllUsersStmt,
		listInvitesForOrgStmt:         q.listInvitesForOrgStmt,
		listOrganizationsStmt:         q.listOrganizationsStmt,
		markInviteUsedStmt:            q.markInviteUsedStmt,
		setUserAdminStmt:              q.setUserAdminStmt,
		updateOrganizationBillingStmt: q.updateOrganizationBillingStmt,
		updateUserOrgStmt:             q.updateUserOrgStmt,
		updateUserPasswordStmt:        q.updateUserPasswordStmt,
	}
}
