// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: invites.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (id, org_id, token, email, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateInviteParams struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	Token     string    `json:"token"`
	Email     string    `json:"email"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.exec(ctx, q.createInviteStmt, createInvite,
		arg.ID,
		arg.OrgID,
		arg.Token,
		arg.Email,
		arg.ExpiresAt,
	)
	return err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites
WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteInviteStmt, deleteInvite, id)
	return err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT id, org_id, token, email, used_at, created_at, expires_at FROM invites
WHERE token = $1 AND used_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetInviteByToken(ctx context.Context, token string) (Invite, error) {
	row := q.queryRow(ctx, q.getInviteByTokenStmt, getInviteByToken, token)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Token,
		&i.Email,
		&i.UsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const markInviteUsed = `-- name: MarkInviteUsed :exec
UPDATE invites
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkInviteUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.markInviteUsedStmt, markInviteUsed, id)
	return err
}
