// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Organization struct {
	ID                   uuid.UUID      `json:"id"`
	Name                 string         `json:"name"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
	StripeCustomerID     sql.NullString `json:"stripe_customer_id"`
	StripeSubscriptionID sql.NullString `json:"stripe_subscription_id"`
	Plan                 sql.NullString `json:"plan"`
	BillingEmail         sql.NullString `json:"billing_email"`
}

type User struct {
	ID             uuid.UUID     `json:"id"`
	Email          string        `json:"email"`
	PasswordHash   string        `json:"password_hash"`
	CreatedAt      sql.NullTime  `json:"created_at"`
	UpdatedAt      sql.NullTime  `json:"updated_at"`
	OrganizationID uuid.NullUUID `json:"organization_id"`
}
