// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Organization struct {
	ID                   uuid.UUID      `json:"id"`
	Name                 string         `json:"name"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
	StripeCustomerID     sql.NullString `json:"stripe_customer_id"`
	StripeSubscriptionID sql.NullString `json:"stripe_subscription_id"`
	Plan                 sql.NullString `json:"plan"`
	BillingEmail         sql.NullString `json:"billing_email"`
	IsPaid               bool           `json:"is_paid"`
	OwnerID              uuid.UUID      `json:"owner_id"`
}

type PasswordReset struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID             uuid.UUID     `json:"id"`
	Email          string        `json:"email"`
	PasswordHash   string        `json:"password_hash"`
	CreatedAt      sql.NullTime  `json:"created_at"`
	UpdatedAt      sql.NullTime  `json:"updated_at"`
	OrganizationID uuid.NullUUID `json:"organization_id"`
	IsAdmin        bool          `json:"is_admin"`
}
