// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: organizations.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (id, name)
VALUES ($1, $2)
RETURNING id, name, created_at, updated_at, stripe_customer_id, stripe_subscription_id, plan, billing_email
`

type CreateOrganizationParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.queryRow(ctx, q.createOrganizationStmt, createOrganization, arg.ID, arg.Name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Plan,
		&i.BillingEmail,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, created_at, updated_at, stripe_customer_id, stripe_subscription_id, plan, billing_email FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.queryRow(ctx, q.getOrganizationStmt, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Plan,
		&i.BillingEmail,
	)
	return i, err
}

const updateOrganizationBilling = `-- name: UpdateOrganizationBilling :exec
UPDATE organizations
SET
  stripe_customer_id = $2,
  stripe_subscription_id = $3,
  plan = $4,
  updated_at = NOW()
WHERE id = $1
`

type UpdateOrganizationBillingParams struct {
	ID                   uuid.UUID      `json:"id"`
	StripeCustomerID     sql.NullString `json:"stripe_customer_id"`
	StripeSubscriptionID sql.NullString `json:"stripe_subscription_id"`
	Plan                 sql.NullString `json:"plan"`
}

func (q *Queries) UpdateOrganizationBilling(ctx context.Context, arg UpdateOrganizationBillingParams) error {
	_, err := q.exec(ctx, q.updateOrganizationBillingStmt, updateOrganizationBilling,
		arg.ID,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.Plan,
	)
	return err
}
