// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: passwordResets.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPasswordReset = `-- name: CreatePasswordReset :exec
INSERT INTO password_resets (id, user_id, token, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreatePasswordResetParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.exec(ctx, q.createPasswordResetStmt, createPasswordReset,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
	)
	return err
}

const deletePasswordReset = `-- name: DeletePasswordReset :exec
DELETE FROM password_resets WHERE token = $1
`

func (q *Queries) DeletePasswordReset(ctx context.Context, token string) error {
	_, err := q.exec(ctx, q.deletePasswordResetStmt, deletePasswordReset, token)
	return err
}

const getPasswordResetByToken = `-- name: GetPasswordResetByToken :one
SELECT id, user_id, token, expires_at, created_at FROM password_resets WHERE token = $1
`

func (q *Queries) GetPasswordResetByToken(ctx context.Context, token string) (PasswordReset, error) {
	row := q.queryRow(ctx, q.getPasswordResetByTokenStmt, getPasswordResetByToken, token)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
